### ISSUE TITLE
IDEA: add Sentry integration

### ISSUE THREAD

**Issue by krystofl** [Ecogate/eglogging#2]
@marekl here's an idea:

we could add a Sentry integration to eglogging. Here's how it would work in practice

1. (optional) give appropriate sentry ID / URL to eglogging
2. whenever a log message of severity ERROR or worse is recorded, if we got a Sentry URL in step 1, also tell Sentry about the error

Thoughts?

**Comment by marekl** [comment]
Would this catch unhanded exceptions?

**Comment by krystofl** [comment]
No, but those already get caught because Sentry is initialized in each script. This is in addition to doing that.

**Comment by krystofl** [comment]
Good news: this behavior is already implemented by Sentry, and is in fact the default behavior - so it was already turned on!

Ref: https://docs.sentry.io/platforms/python/logging/
